server:
  address: 127.0.0.1
  port: ${PORT:18081}
  error:
    include-message: never
    include-stacktrace: never
spring:
  config:
    import: "optional:file:./.env[.properties]"
  datasource:
    url: jdbc:h2:mem:lab1;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  sql:
    init:
      mode: always
app:
  demo:
    login: ${APP_LOGIN:student}
    password: ${APP_PASSWORD}
    other-login: ${APP_OTHER_LOGIN:other}
    other-password: ${APP_OTHER_PASSWORD:}
